project: 'reference_tracks'
mode: 'extract_baseline'

cases:
    # erin:
    #     year: 2025
    #     basin: north_atlantic

    # harvey:
    #     year: 2017
    #     basin: north_atlantic

    # irma:
    #     year: 2017
    #     basin: north_atlantic

    # maria:
    #     year: 2017
    #     basin: north_atlantic

    # ophelia:
    #     year: 2017
    #     basin: north_atlantic

    # michael:
    #     year: 2018
    #     basin: north_atlantic

    # dorian:
    #     year: 2019
    #     basin: north_atlantic

    # lorenzo:
    #     year: 2019
    #     basin: north_atlantic

    # iota:
    #     year: 2020
    #     basin: north_atlantic

    # ian:
    #     year: 2022
    #     basin: north_atlantic

    # lee:
    #     year: 2023
    #     basin: north_atlantic

    # beryl:
    #     year: 2024
    #     basin: north_atlantic

    # milton:
    #     year: 2024
    #     basin: north_atlantic

    helene:
        year: 2024
        basin: north_atlantic

    # lan:
    #     year: 2017
    #     basin: west_pacific

    # hato:
    #     year: 2017
    #     basin: west_pacific

    # mawar:
    #     year: 2023
    #     basin: west_pacific

    # yagi:
    #     year: 2024
    #     basin: west_pacific

    # amphan:
    #     year: 2020
    #     basin: north_indian

    # debbie:
    #     year: 2017
    #     basin: southern_pacific

ibtracs_source_data: "/fcn3_cyclones/ibtracs_data/ibtracs.ALL.list.v04r01.csv"

data_source:
    h5_era5_train:
        years: "1980-2016"
        source:
            _target_: src.data.localh5.LocalArchiveHDF5
            dirs: "/lustre/fsw/coreai_climate_earth2/datasets/era5_75var/train"
            metadata_file: "/lustre/fsw/coreai_climate_earth2/datasets/era5_75var/metadata/data.json"

    h5_era5_test:
        years: 2017
        source:
            _target_: src.data.localh5.LocalArchiveHDF5
            dirs: "/lustre/fsw/coreai_climate_earth2/datasets/era5_75var/test"
            metadata_file: "/lustre/fsw/coreai_climate_earth2/datasets/era5_75var/metadata/data.json"

    h5_era5_oos:
        years: "2018-2022"
        source:
            _target_: src.data.localh5.LocalArchiveHDF5
            dirs: "/lustre/fsw/coreai_climate_earth2/tkurth/73varQ-hourly/out_of_sample"
            metadata_file: "/lustre/fsw/coreai_climate_earth2/tkurth/73varQ-hourly/metadata/data.json"

    ncar_era5:
        years: "2023-2024"
        source:
            _target_: earth2studio.data.NCAR_ERA5

    gfs:
        years: "2025"
        source:
            _target_: earth2studio.data.GFS

orography_path: '/fcn3_cyclones/checkpoints/fcn2_sc2_edim45_layers10_finetune_2013-2016_8step_centered_4member/flexible_5epochs/orography.nc'
store_dir: "./outputs"

cyclone_tracking:
    vars: ['msl', 'u10m', 'v10m', 'z300', 'z500']
    detect_cmd: 'DetectNodes --verbosity 0 --mergedist 6 --closedcontourcmd _DIFF(z300,z500),-58.8,6.5,0;msl,200.,5.5,0 --searchbymin msl --outputcmd msl,min,0;_VECMAG(u10m,v10m),max,5;height,min,0'
    stitch_cmd: 'StitchNodes --in_fmt lon,lat,msl,wind_speed,height --range 8.0 --mintime 54h --maxgap 4 --out_file_format csv --threshold wind_speed,>=,10.,10;lat,<=,50.,10;lat,>=,-50.,10;height,<=,150.,10'
    keep_raw_data: False
    use_ram: True
    print_te_output: False
